### ISSUE TITLE
Address eCTF student feedback

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/ctf-scoreboard-archive#17]
1. The flags/min feed that is shown doesn’t really make much sense
2. On the challenges list, it’d be nice to show the challenge name rather than just the point value
3. Also on the challenges list, the color-coding is a bit confusing and hard to notice

**Comment by rbclark** [comment]
1. I agree it doesn't make sense for the eCTF because the code for that wasn't really designed for use on the eCTF, it was more designed for a shorter competition. I feel the code for that does act a bit strange even in short competitions and someone should probably review it. That does require someone being knowledgeable about the d3 library though.
2. This one I don't really agree with, perhaps for their competition that is the case however I feel the point value is more important information to the competitors then the actual name of the challenge. Also since we have recently been having multiple challenges with 50 or 100 points, this would be really confusing.
3. We can take a second look at the coloring, I can't think exactly what it looks like off the top of my head.

**Comment by Bialogs** [comment]
1. Will be looking into this in a separate issue
2. Agree with @rbclark 
3. has been handled

**Comment by dtwalter** [comment]
Sorry for the late comment here, but just noticing this now... as for (2) - the suggestion was to show BOTH the point value and the challenge name.  I agree that not showing point value would be confusing, but it's also confusing/annoying to not see the name from the scoreboard since some challenges have the same number of points so they aren't uniquely identified from the point value.

The recent google CTF had a nice scoreboard UI, which showed name of challenge and then point value on mouseover.  See https://capturetheflag.withgoogle.com/challenges/

**Comment by rbclark** [comment]
In that case I feel like a mouseover text with the challenge name or something similar would be appropriate. This is a change I would be okay with trying out, reopening for now.
